server:
    port: 8080

spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    devtools:
        restart:
            enabled: true
            exclude: static/**,templates/**

    jade4j:
        caching: false

    jpa:
        show-sql: true

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://188.131.176.163/spring_blog_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root

        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    redis:
      host: 188.131.176.163
      port: 6379
      default_expire_time: 86400

    resources:
          add-mappings: true
          cache-period:
          chain:
            cache: true
            gzipped: false
            html-application-cache: false
            strategy:
              content:
                enabled: false
                paths: /**
              fixed:
                enabled: false
                paths: /**
          static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


logging:
  level:
    org.springframework.web: ERROR
    com.ispoet.blog: DEBUG
